services:
  mysql_test:
    image: "mysql:8.0.39-bookworm"
    container_name: mysql_test
    volumes:
      - "mysql_test:/var/lib/mysql"
    tty: true
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_PORT: 3306
      MYSQL_HOST: localhost
    profiles: ["mysql-test"]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u ${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      test-bridge:
        aliases:
          - mysql_test

  redis_test:
    image: "redis:7.4.1-bookworm"
    container_name: redis_test
    volumes:
      - "redis_test:/data"
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 10s
      retries: 3

    profiles: ["redis-test"]
    networks:
      test-bridge:
        aliases:
          - redis_test

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: "tests"
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    environment:
      - APP__APPLICATION__HOST=0.0.0.0
      - APP__DATABASE__HOST=mysql_test
      - APP__REDIS_URI=redis://redis_test:6379
    depends_on:
      mysql_test:
        condition: service_healthy
      redis_test:
        condition: service_healthy
    tty: true
    profiles: ["tests"]
    networks:
      - test-bridge

networks:
  test-bridge:

volumes:
  mysql_test: {}
  redis_test: {}
